# BOT CONFIGURATION
BOT_TOKEN = "TOKEN_HERE"

# DATABASE CONFIGURATION
DATABASE_NAME = "DATABASE_NAME_HERE"
DATABASE_URL = "DATABASE_URL_HERE"
CLUSTER_NAME = "CLUSTER_NAME_HERE"


# BOT SETTINGS
DEFAULT_PREFIX = "DEFAULT_PREFIX_HERE"
BOT_ADMIN = "BOT_ADMIN_USER_IDS"
EMBED_COLOR = "DEFAULT_EMBED_COLOR"
OWNER_ID = "OWNER_ID_HERE"
SUPPORT_SERVER = "SUPPORT_SERVER_INVITE_HERE"

# GAME LOGGING CHANNELS
STATUS_LOG = None
ERROR_LOG = None
ADMIN_LOGS = None # Add channel ids here

# EMOTES AND ICONS
EMOTE_INFO = None
EMOTE_SUCCESS = None
EMOTE_ERROR = None # Add emojis and icons id here
