# BOT CONFIGURATION
BOT_TOKEN = None

# DATABASE CONFIGURATION
DATABASE_NAME = None
DATABASE_URL = None
CLUSTER_NAME = None
COLLECTION_NAME = None


# BOT SETTINGS
DEFAULT_PREFIX = None
BOT_ADMIN = None 
EMBED_COLOR = None
OWNER_ID = None
SUPPORT_SERVER = None

# GAME LOGGING CHANNELS
STATUS_LOG = None
ERROR_LOG = None
ADMIN_LOGS = None

# EMOTES AND ICONS
EMOTE_INFO = None
EMOTE_SUCCESS = None
EMOTE_ERROR = None


